### This function cleans the unwanted characters from code generated by LLM.

def safe_execute(raw):
    # removes markdown
    codee = raw.replace("```python","").replace("```", "").strip()

    # removes outer spaces
    if (codee.startswith("'") and codee.endswith("'") or codee.startswith('"') and codee.endswith('"')):
        codee = codee[1:-1]

    unsafe_words = ["import", "__", "os", "os.", "sys", "open(", "exec", "eval", "import os"]

    if any(word in codee for word in unsafe_words):
        raise ValueError(f"Unsafe code detected.")
    
    return codee